mongodb:
  image: mongo:4.0
  container_name: mongo-slpdb
  ports:
    - "3607:27017"
  volumes:
    - ../mongodb:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
  restart: always

slpdb:
  build: .
  dockerfile: Dockerfile
  container_name: slpdb
  links:
    - mongodb
#  ports:
#    - "3003:3000"
#    - "9229:9229"
  volumes:
    - ../leveldb:/home/safeuser/SLPDB/_leveldb
  restart: always

slpserve:
  build: ./slpserve/
  dockerfile: Dockerfile
  container_name: slpserve-testnet
  links:
    - mongodb
  ports:
    - "12300:4000"
  restart: always
