mongodb:
  image: mongo:4.0
  container_name: mongo-slpdb
  ports:
    - "12301:27017"
  volumes:
    - ../mongodb:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
  restart: always

slpdb:
  #build: .
  #dockerfile: Dockerfile
  image: christroutner/slpdb-mainnet_slpdb:0.14.1
  container_name: slpdb
  links:
    - mongodb
#  depends_on:
#    - mongodb
#  ports:
#    - "3003:3000"
#    - "9229:9229"
  volumes:
    - ../leveldb:/home/safeuser/SLPDB/_leveldb
  restart: always

slpserve:
  #build: ./slpserve/
  #dockerfile: Dockerfile
  image: christroutner/slpdb-mainnet_slpserve:0.14.1
  container_name: slpserve
  links:
    - mongodb
  ports:
    - "12300:4000"
  restart: always
